const fs = require('fs');

const p1 = JSON.parse(fs.readFileSync('/Users/umurey/.gemini/antigravity/brain/665f804e-a806-4e04-bb93-4515e7cd04cb/scratch/ja_patch_1.json', 'utf8'));
const p2 = JSON.parse(fs.readFileSync('/Users/umurey/.gemini/antigravity/brain/665f804e-a806-4e04-bb93-4515e7cd04cb/scratch/ja_patch_2.json', 'utf8'));

const landStr = JSON.stringify(p1.landwirtschaft, null, 2).split('\n').map(l => '    ' + l).join('\n').trim();
const schiffStr = JSON.stringify(p2.schiffbau, null, 2).split('\n').map(l => '    ' + l).join('\n').trim();

const replacement = `    "trinkwasser": {
      "metaTitle": "安全な飲料水用PP-R配管システム | K Aqua",
      "metaDesc": "病院や公共施設向けのK Aqua飲料水ネットワーク。レジオネラ菌予防、DVGW/KTW認定、最高の水質衛生。",
      "heroEyebrow": "K Aqua 飲料水インフラ",
      "heroTitle": "純粋さと",
      "heroSubtitle": "衛生。",
      "heroDesc": "水は最も重要な食品です。私たちの配管システムは、水源から蛇口まで、品質を一切損なうことなく安全に輸送することを保証します。世界で最も厳格な衛生基準に従って認定されています。",
      "heroBtnPrimary": "飲料水ネットワークの計画",
      "heroBtnSecondary": "衛生基準を読む",
      "section1Eyebrow": "極めて重要な要素",
      "section1Title": "健康への妥協は許されない。",
      "section1Lead": "飲料水の設備、特に病院、学校、ホテルにおいて、衛生上の不備は致命的な結果を招く可能性があります。",
      "section1P1": "停滞水、錆、スケーリング（水垢）は、レジオネラ菌やその他の病原菌の理想的な温床となります。金属製のパイプは時間とともに腐食し、水質に影響を与えます。",
      "section1P2": "K Aquaシステムは、これらのリスクを物理的に排除します。滑らかな表面、化学的中立性、そして完全に漏れのない接続。",
      "section1P3": "当社のPP-RおよびPPRCTシステムは、最高レベルの水衛生と安全性を必要とするすべての人々のための論理的な選択です。",
      "section2Eyebrow": "テクノロジー",
      "section2Title": "完璧な水質のためのエンジニアリング。",
      "section2Lead": "当社のパイプが何十年にもわたって純粋な飲料水を保証する技術的理由。",
      "scroll1Title": "鏡のように滑らかな内面",
      "scroll1Desc": "内部の粗さが0.007mmであるため、バクテリアやバイオフィルムが定着する場所がありません。堆積物やスケーリング（水垢）は実質的に不可能です。",
      "scroll2Title": "味と匂いの中立性",
      "scroll2Desc": "K Aqua PP-Rは完全に無毒で中立です。飲料水に金属イオン、化学物質、味、臭いを放出しません。",
      "scroll3Title": "不透明性と光の遮断",
      "scroll3Desc": "当社のパイプは完全に不透明です。これにより、光がパイプラインに浸透するのを防ぎ、藻類の繁殖のリスクを排除します。",
      "scroll4Title": "熱消毒への耐性",
      "scroll4Desc": "レジオネラ菌と戦うために、システムは病院での熱消毒（例：70°C以上でのフラッシング）に問題なく耐えることができます。",
      "section3Eyebrow": "システムの利点",
      "section3Title": "インストーラーとプランナーにとっての利点。",
      "section3Lead": "衛生だけではありません。当社のシステムは、プロジェクトの計画と実行においても比類のない利点を提供します。",
      "bento1Title": "100%の無鉛（鉛フリー）",
      "bento1Desc": "真鍮や青銅の継手を使用するシステムとは異なり、完全なK Aqua PP-Rシステムは100%鉛フリーであり、将来の最も厳しい規制にも準拠しています。",
      "bento2Title": "絶対的な耐食性",
      "bento2Desc": "水のpH値や硬度に関係なく、K Aquaのパイプは錆びたり、孔食を起こしたりしません。",
      "bento3Title": "騒音の低減",
      "bento3Desc": "PP-Rの優れた遮音特性により、水流やウォーターハンマーの騒音が最小限に抑えられ、ホテルや住宅での快適性が向上します。",
      "bento4Title": "国際認証",
      "bento4Desc": "DVGW（ドイツ）、WRAS（英国）、KTW、KIWAなど。世界中の主要な飲料水基準によって検証され、承認されています。",
      "bento5Title": "迅速な設置",
      "bento5Desc": "軽量で均一なポリフュージョン溶接により、銅管や鋼管システムと比較して設置時間を大幅に節約できます。",
      "bento6Title": "高い流量性能",
      "bento6Desc": "摩擦損失が少ないため、必要な水圧が維持され、より小さなパイプ寸法の使用が可能になり、コストを節約できる場合があります。",
      "bento7Title": "持続可能性",
      "bento7Desc": "製造時のエネルギー消費が少なく、完全にリサイクル可能な材料であるPP-Rは、金属製の配管システムの環境に優しい代替品です。",
      "timelineEyebrow": "プロジェクト実行",
      "timelineLead": "安全な飲料水ネットワークへのステップ。",
      "timeline1Year": "ステップ 1",
      "timeline1Title": "ネットワークサイジング",
      "timeline1Text": "停滞を避けるためのパイプ径の正確な計算と、すべての蛇口で十分な流量の確保。",
      "timeline2Year": "ステップ 2",
      "timeline2Title": "ルーティングと計画",
      "timeline2Text": "冷水ラインと温水ラインを分離して不要な熱伝達を防ぎ、デッドレグ（水が滞留する分岐）を避ける設計。",
      "timeline3Year": "ステップ 3",
      "timeline3Title": "衛生的な設置",
      "timeline3Text": "汚染を防ぐための現場での清潔な取り扱いと、継ぎ目のない接続のためのプロフェッショナルな溶接。",
      "timeline4Year": "ステップ 4",
      "timeline4Title": "フラッシングと圧力テスト",
      "timeline4Text": "試運転前の徹底的なフラッシング（洗浄）と、システムの完全性を確認するための厳格な圧力テスト。",
      "timeline5Year": "ステップ 5",
      "timeline5Title": "安全な引き渡し",
      "timeline5Text": "最高水準の衛生基準を満たした、完全に機能し、文書化された飲料水ネットワークの引き渡し。",
      "section4Title": "目に見える安全性",
      "section4P1": "高品質の飲料水設備の価値は、それが何十年もの間、静かにそして安全に機能することにあります。",
      "section4P2": "K Aquaを選択することは、建物の住民とユーザーの健康と安全に投資することです。",
      "stat1Value": "0.007",
      "stat1Unit": "mm",
      "stat1Label": "内部表面粗さ",
      "stat2Value": "100",
      "stat2Unit": "%",
      "stat2Label": "耐腐食性",
      "stat3Value": "50+",
      "stat3Unit": "年",
      "stat3Label": "システムの寿命",
      "stat4Value": "0",
      "stat4Unit": "%",
      "stat4Label": "有毒物質の放出",
      "ctaTitle": "最高の水質を設計する。",
      "ctaDesc": "次のプロジェクトにおいて、飲料水の衛生と安全性を確保するためのお手伝いをします。",
      "ctaBtn": "コンサルティングを依頼"
    },
    "landwirtschaft": ${landStr},
    "schiffbau": ${schiffStr}
  }
}`;

fs.writeFileSync('trink_plus_land_schiff.txt', replacement);
