import json

def get_text(city):
    text = f"""<h2>Hochleistungs-PP-R und PP-RCT Rohrleitungssysteme für Industrie und Gebäudetechnik in {city}</h2>
<p>Die stetig wachsenden Anforderungen an moderne Architektur, komplexe industrielle Infrastruktur und zukunftsweisende Bauprojekte in {city} verlangen nach Rohrleitungssystemen, die höchste Maßstäbe an Sicherheit, Hygiene, Langlebigkeit und Effizienz setzen. K-Aqua, als international renommierter deutscher Hersteller, bietet dem anspruchsvollen B2B-Markt in {city} ein exzellentes und umfassendes Portfolio an PP-R (Polypropylen-Random-Copolymer) und PP-RCT (Polypropylen mit erhöhter Temperaturbeständigkeit) Kunststoffrohrsystemen. Unsere hochmodernen Lösungen sind präzise und kompromisslos auf die spezifischen Anforderungen von Ingenieurbüros, Fachplanern, kommunalen Bauherren, Generalunternehmern und Industrieunternehmen in der Region zugeschnitten. Wir entwickeln und liefern hochbelastbare, extrem druckfeste und absolut korrosionsfreie Rohrleitungssysteme für kritische Anwendungen wie die Trinkwasserversorgung, anspruchsvolle Klimatechnik, Fernwärme- und Fernkältesysteme sowie den hochsicheren Transport aggressiver industrieller Medien.</p>
<h3>100 % korrosionsfreie Lösungen für die Trinkwasserversorgung und sensible Gesundheitseinrichtungen in {city}</h3>
<p>In öffentlichen Gebäuden, Gesundheitszentren, Laboren und Krankenhäusern in {city} gelten extrem strenge gesetzliche und hygienische Vorgaben für die Trinkwasserqualität. Traditionelle metallische Rohrsysteme, wie solche aus Kupfer oder verzinktem Stahl, bergen kontinuierlich das signifikante Risiko von Korrosion, gefährlicher Schwermetallabgabe oder massiven Kalkablagerungen. Diese Inkrustationen dienen häufig als Nährboden für potenziell tödliche Krankheitserreger wie Legionellen und andere Biofilme. K-Aqua PP-R und PP-RCT Leitungssysteme sind hingegen zu 100 % korrosionsbeständig, vollkommen geschmacks- sowie geruchsneutral und erfüllen die allerhöchsten globalen hygienischen Standards (wie DVGW, SKZ, WRAS). Die extrem glatte, porenfreie Innenoberfläche der Rohre verhindert jegliche Form von Ablagerungen dauerhaft und garantiert einen konstant niedrigen Reibungsverlust. Dank der fortschrittlichen und homogenen Verschweißungstechnik, dem Polyfusionsschweißen, entstehen absolut leckagefreie und unzertrennliche Verbindungen. Dieses Verfahren eliminiert das Risiko von Wasserschäden in sensiblen Gebäudeinfrastrukturen in {city} vollständig und bietet eine Sicherheit, die herkömmliche mechanische Verbindungen niemals erreichen können.</p>
<h3>Hocheffiziente HVAC-Systeme, Fernkälte und industrielle Kühlkreisläufe für die Wirtschaft in {city}</h3>
<p>Die energetisch optimale Klimatisierung von gewerblichen Großprojekten, weitläufigen Bürokomplexen, gigantischen Einkaufszentren und hochkomplexen Industrieanlagen (HVAC) ist ein zentraler Wachstumsmarkt in {city}. K-Aqua PP-RCT Rohrsysteme bieten für diese anspruchsvollen Anwendungen herausragende thermodynamische Eigenschaften, die den Energieverbrauch drastisch senken. Die im direkten Vergleich zu herkömmlichen Metallrohren signifikant geringere Wärmeleitfähigkeit des PP-RCT Kunststoffs sorgt für eine hervorragende natürliche Isolationswirkung. Diese Eigenschaft minimiert den Energieverlust über lange Transportstrecken und reduziert das Risiko gefährlicher Kondenswasserbildung bei Kaltwassersystemen erheblich. Dies trägt massiv und messbar zur Steigerung der Gesamtenergieeffizienz von Gebäuden (Green Building Zertifizierungen) bei. Mit einer extrem breiten und tiefen Auswahl an SDR-Klassen (Standard Dimension Ratio) und PN-Druckstufen halten unsere High-Tech-Systeme auch den extremen Betriebsdrücken und permanenten Belastungen großer industrieller Kühl- und Heizanlagen in {city} vollkommen mühelos stand.</p>
<h3>Maximale Sicherheit für Chemieindustrie, Geothermie und aggressiven Medientransport in {city}</h3>
<p>Die stark wachsende und diversifizierte Industrielandschaft in {city}, welche Sektoren wie die chemische Verarbeitung, pharmazeutische Produktion und moderne Energieerzeugung umfasst, benötigt absolut ausfallsichere Systeme. Für den extrem sicheren Transport von hochaggressiven Chemikalien, toxischem Prozesswasser, Druckluft oder stark mineralhaltigen geothermischen Flüssigkeiten ist die überragende chemische Beständigkeit unserer PP-R und PP-RCT Rohre schlichtweg unerlässlich. Im radikalen Gegensatz zu traditionellen Materialien wie legiertem Stahl, Edelstahl oder Kupfer werden K-Aqua Rohre durch saure, alkalische oder anderweitig korrosive Medien in keiner Weise angegriffen. Diese Resistenz garantiert eine absolut sichere, unterbrechungsfreie Prozessführung und eine nachgewiesene operative Lebensdauer von weit über 50 Jahren unter härtesten Bedingungen. Dies senkt die langfristigen Wartungskosten (OPEX) sowie die ungeplanten Ausfallzeiten von kritischen Industrieanlagen in {city} auf ein absolutes, kalkulierbares Minimum und bietet internationalen Investoren sowie lokalen Betreibern maximale finanzielle und betriebliche Investitionssicherheit.</p>
<h3>Umweltfreundlichkeit und Nachhaltigkeit für grüne Bauprojekte in {city}</h3>
<p>Neben den herausragenden technischen und wirtschaftlichen Vorteilen leisten K-Aqua PP-R und PP-RCT Systeme einen immensen Beitrag zum globalen Umweltschutz und zur Erreichung von Nachhaltigkeitszielen in {city}. Unsere Kunststoffrohre sind zu 100 % recycelbar und weisen im Vergleich zu Metallrohren eine deutlich günstigere Ökobilanz (Life Cycle Assessment) auf. Der Energieaufwand bei der Herstellung von Polypropylen ist signifikant geringer als bei der Verhüttung von Stahl oder Kupfer. Darüber hinaus sorgt die extrem lange Lebensdauer von über fünf Jahrzehnten für eine drastische Reduktion des Ressourcenverbrauchs, da ein vorzeitiger Austausch der Systeme vermieden wird. In einer Zeit, in der Gebäudezertifizierungen wie LEED, BREEAM oder DGNB in {city} immer mehr an Bedeutung gewinnen, bieten K-Aqua Rohrleitungssysteme Bauherren und Entwicklern die perfekte Lösung, um höchste ökologische Standards zu erfüllen und gleichzeitig eine unübertroffene technische Performance zu garantieren.</p>
<h3>K-Aqua – Premium 'Made in Germany' Qualität für zukunftsweisende B2B-Projekte in {city}</h3>
<p>Als überaus zuverlässiger und innovativer Systemlieferant stehen wir unseren geschätzten B2B-Partnern in {city} mit tiefgreifendem technischen Know-how, einem exzellenten, projektbegleitenden Service und einem lückenlosen Produktsortiment jederzeit zur Seite. Unser durchdachtes System umfasst nicht nur Rohre, sondern auch eine immense Vielfalt an Formteilen, Ventilen und Verteilern, die alle perfekt aufeinander abgestimmt sind und extrem schnelle, hochgradig wirtschaftliche Installationsprozesse direkt auf der Baustelle ermöglichen. Das geringe Eigengewicht der PP-R und PP-RCT Materialien erleichtert die Logistik und das Handling vor Ort enorm, was die Arbeitskosten und die benötigte Installationszeit drastisch reduziert. Mit der bewussten Entscheidung für K-Aqua wählen Bauingenieure, Architekturplaner und weitsichtige Projektentwickler in {city} kompromisslos zukunftssichere, hochdruckbeständige, wartungsfreie und ökologisch nachhaltige Rohrleitungssysteme. Unsere Lösungen optimieren die Rentabilität, die ökologische Fußabdruck-Bilanz und die operative Sicherheit industrieller und gewerblicher Großprojekte nachhaltig und setzen den definitiven Standard für die nächste Generation der Gebäudetechnik.</p>"""
    return text.replace('\n', '\\n')

print(get_text('Katar'))
