const fs = require('fs');
const out = {
  "productNames": {
    "accessories_backing-flange": "بیکنگ فلانج پی پی-اسٹیل (SF/BF)",
    "accessories_flat-gasket-for-unions": "یونینز کے لیے فلیٹ گسکیٹ PP-R",
    "accessories_flat-gasket": "فلیٹ گسکیٹ",
    "accessories_pipe-clamps": "پائپ کلیمپ",
    "accessories_plug": "PP-R پائپ پلگ",
    "fittings_cap": "PP-R اینڈ کیپ",
    "fittings_cross-over-pipe": "PP-R کراس اوور پائپ",
    "fittings_cross-over": "PP-R کراس اوور",
    "fittings_cross": "PP-R کراس پیس",
    "fittings_elbow-45-female-male": "PP-R ایلبو 45° (I/A)",
    "fittings_elbow-45": "PP-R معیاری ایلبو 45°",
    "fittings_elbow-90-female-male": "PP-R ایلبو 90° (I/A)",
    "fittings_elbow-90": "PP-R معیاری ایلبو 90°",
    "fittings_electrofusion-socket": "الیکٹرو فیوژن ساکٹ",
    "fittings_flange-adaptor": "فلانج اڈاپٹر",
    "fittings_reducing-bush": "ریڈیوسنگ بش",
    "fittings_reducing-tee-large": "PP-R ریڈیوسنگ ٹی (بڑا)",
    "fittings_reducing-tee": "ریڈیوسنگ ٹی",
    "fittings_socket": "PP-R ساکٹ",
    "fittings_tee": "PP-R ٹی پیس",
    "pipes_k-fiber-pipe-pp-r-sdr-11": "کے-فائبر پائپ PP-R SDR 11",
    "pipes_k-fiber-pipe-pp-r-sdr-17": "کے-فائبر پائپ PP-R SDR 17",
    "pipes_k-fiber-pipe-pp-r-sdr-7-4": "کے-فائبر پائپ PP-R SDR 7.4",
    "pipes_k-fiber-pipe-pp-r-sdr-9": "کے-فائبر پائپ PP-R SDR 9",
    "pipes_k-fiber-pipe-pp-rct-sdr-7-4": "کے-فائبر پائپ PPRCT SDR 7.4",
    "pipes_k-fiber-uv-pipe-pp-r-sdr-7-4": "کے-فائبر یووی-پائپ PP-R SDR 7.4",
    "pipes_k-fiber-uv-pipe-pp-r-sdr-7-4_desc": "بیرونی استعمال کے لیے خصوصی یووی پروٹیکشن جیکٹ کے ساتھ ملٹی لیئر کمپوزٹ پائپ (SDR 7.4 PP-R)۔",
    "pipes_k-fiber-uv-pipe-pp-rct-sdr-7-4": "کے-فائبر یووی-پائپ PPRCT SDR 7.4",
    "pipes_k-fiber-uv-pipe-pp-rct-sdr-7-4_desc": "سخت بیرونی تنصیبات کے لیے کالی یووی پروٹیکشن پرت کے ساتھ اعلی کارکردگی کا کمپوزٹ پائپ (PPRCT)۔",
    "pipes_k-fiberclima-pipe-pp-rct-sdr-11": "کے-فائبر کلائما پائپ PPRCT SDR 11",
    "pipes_k-pipe-pp-r-sdr-11": "کے-پائپ PP-R SDR 11",
    "pipes_k-pipe-pp-r-sdr-6": "کے-پائپ PP-R SDR 6",
    "pipes_k-pipe-pp-rct-sdr-7-4": "کے-پائپ PPRCT SDR 7.4",
    "pipes_k-pipe-purple-pp-r-sdr-11": "کے-پائپ پرپل PP-R SDR 11",
    "tools_butt-welding-machine-90-250": "بٹ ویلڈنگ مشین d90-d250",
    "tools_drilling-tool-for-weld-in-saddle": "ویلڈ ان سیڈل کے لیے ڈرلنگ ٹول",
    "tools_electrofusion-machine": "الیکٹرو فیوژن ویلڈنگ مشین",
    "tools_hand-welding-machine-20-32": "ہینڈ ویلڈنگ مشین d20-d32",
    "tools_hand-welding-machine-20-32_desc": "d20 سے d32 ملی میٹر کے چھوٹے طول و عرض کے لیے مکمل سیٹ کے طور پر کمپیکٹ ساکٹ ویلڈنگ ڈیوائس۔",
    "tools_hand-welding-machine-20-63": "ہینڈ ویلڈنگ مشین d20-d63",
    "tools_hand-welding-machine-20-63_desc": "d20 سے d63 ملی میٹر کے پائپوں کے لیے سیٹ میں ورسٹائل ساکٹ ویلڈنگ مشین۔",
    "tools_hand-welding-machine-mirror-50-125": "ہینڈ ویلڈنگ مشین (صرف آئینہ) 50–125",
    "tools_pipe-cutter-20-40": "ریچیٹ پائپ کٹر d20-d40",
    "tools_pipe-cutter-50-125-114": "پائپ کٹر 1 1/4",
    "tools_pipe-cutter-50-125": "پروفیشنل پائپ کٹر d50-d125",
    "tools_repairing-plug": "مرمت پلگ",
    "tools_welding-machine-50-125": "ویلڈنگ مشین d50-d125",
    "tools_welding-tool-for-repairing-plug": "مرمت پلگ کے لیے ویلڈنگ ٹول",
    "tools_welding-tool-for-weld-in-saddles": "ویلڈ ان سیڈل کے لیے ویلڈنگ ٹول",
    "tools_welding-tool": "ویلڈنگ ٹول",
    "transition-fittings_adaptor-socket-female-thread": "اڈاپٹر ساکٹ (IG)",
    "transition-fittings_adaptor-socket-male-thread": "اڈاپٹر ساکٹ (AG)",
    "transition-fittings_elbow-90-male-thread": "PP-R ٹرانزیشن ایلبو 90° (AG)",
    "transition-fittings_elbow-bracket-90-female-thread": "وال بریکٹ ایلبو 90° (IG)",
    "transition-fittings_elbow-bracket-90-female-thread_desc": "فٹنگز (IG) کی محفوظ دیوار چڑھانے کے لیے یک طرفہ زاویہ دیوار بریکٹ۔",
    "transition-fittings_elbow-wall-bracket-90-female-thread": "ڈبل وال بریکٹ ایلبو 90° (IG)",
    "transition-fittings_elbow-wall-bracket-90-female-thread_desc": "انتہائی مستحکم کنکشن کے لیے دو طرفہ دیوار چڑھانا۔",
    "transition-fittings_metal-union-female-thread-brass": "پیتل کی دھاتی یونین CW617N (IG)",
    "transition-fittings_metal-union-female-thread": "PP-R نٹ کے ساتھ یونین (IG)",
    "transition-fittings_metal-union-male-thread-brass": "پیتل کی دھاتی یونین CW617N (AG)",
    "transition-fittings_metal-union-male-thread": "PP-R نٹ کے ساتھ یونین (AG)",
    "transition-fittings_tee-90-female-thread": "ٹی پیس 90° (IG)",
    "transition-fittings_tee-90-male-thread": "ٹی پیس 90° (AG)",
    "transition-fittings_union-for-watermeters": "پانی کے میٹر کے لیے یونین",
    "transition-fittings_union": "PP-R پائپ یونین",
    "valves_adjustable-battery-female-thread": "ایڈجسٹ ایبل بیٹری (IG)",
    "valves_battery-female-thread": "بیٹری (IG)",
    "valves_concealed-valve-chrome-heavy-part": "چھپا ہوا والو کروم: بھاری اوپری حصہ",
    "valves_concealed-valve-chrome-light-part": "چھپا ہوا والو کروم: ہلکا اوپری حصہ",
    "valves_elongation-pieces": "توسیعی ٹکڑے",
    "valves_pp-r-ball-valve-ball-in-pp": "PP-R بال والو (PP-بال)",
    "valves_pp-r-ball-valve-brass": "PP-R بال والو (پیتل کی بال، کروم پلیٹڈ)",
    "valves_straight-seat-valve-green-handle": "ترچھا والو (اوپری حصہ)",
    "valves_tee-90-female-thread-internal-valve": "ٹی پیس 90° (IG) چھپے ہوئے والو کے لیے",
    "weld-in-saddles_weld-in-saddle-female-thread": "ویلڈ ان سیڈل (IG)",
    "weld-in-saddles_weld-in-saddle-male-thread": "ویلڈ ان سیڈل (AG)",
    "weld-in-saddles_weld-in-saddle": "ویلڈ ان سیڈل"
  }
};
fs.writeFileSync('nav_chunk7_ur.json', JSON.stringify(out, null, 2));
