const fs = require('fs');
const hu = fs.readFileSync('messages/hu.json', 'utf8').split('\n');
const target = hu.slice(3180, 3265).join('\n'); 

const repl = `{
  "guideText": "<h2>Fenntarthatóság és Életciklus-értékelés (LCA)</h2><p>A megfelelő csőrendszer kiválasztása jelentősen befolyásolja egy épület vagy ipari létesítmény CO₂-lábnyomát. A K-Aqua CO₂-kalkulátor átfogó életciklus-elemzést (LCA) tesz lehetővé az EN 15804 szabványnak megfelelően. Ez az elemzés a teljes életciklusra kiterjed: a nyersanyag-kitermeléstől és a termékgyártástól (A1-A3 fázis) a szállításon és telepítésen (A4-A5 fázis) át a használati fázisig (B fázis) és az életciklus végéig (C fázis).</p><p>A hagyományos réz- vagy acélcsövekhez képest a K-Aqua PP-R és PPRCT csövei lényegesen kedvezőbb ökológiai egyenleggel rendelkeznek. A műanyag extrudálásához szükséges alacsonyabb energiaigény, valamint a jóval kisebb súly jelentősen csökkenti a termelés és a szállítás során keletkező CO₂-kibocsátást. Ezenkívül a tükörsima belső felület (mindössze 0,007 mm-es érdesség) rendkívül alacsony áramlási ellenállást biztosít. A Darcy-Weisbach egyenlet alapján ez azt jelenti, hogy a keringető szivattyúknak lényegesen kevesebb energiát (áramot) kell felhasználniuk a folyadék keringtetéséhez a rendszerben.</p><p>Különösen a használati fázisban (B fázis), amely a csőrendszerek esetében gyakran 50 évig vagy tovább tart, ez az energiamegtakarítás masszív CO₂- és költségmegtakarítássá (Teljes Birtoklási Költség, TCO) adódik össze. Az életciklus végén (C fázis) is ökológiai előnyöket kínál a polipropilén, mivel 100%-ban újrahasznosítható, és a körforgásos gazdaság (D modul) értelmében újra felhasználható. Használja ezt a kalkulátort a K-Aqua projektjének ökológiai és ökonómiai megtakarítási potenciáljának pontos és átlátható számszerűsítéséhez.</p>",
  "eyebrow": "Prémium Mérnöki Eszköz",
  "title1": "LCA és TCO Szimulátor",
  "titleGrad": "Pro",
  "lead": "Számítsa ki csőrendszere valós ökológiai és gazdasági hatásait a teljes életciklusa során. Valódi fizikai áramlási modellekkel (Darcy-Weisbach) és EN-kompatibilis LCA fázisokkal.",
  "tabGeometry": "Cső",
  "tabFlow": "Folyadék",
  "tabEnvironment": "Telepítés",
  "tabLogistics": "LCA",
  "dia": "Névleges átmérő",
  "length": "Vezeték hossza",
  "sdrClass": "SDR-Osztály",
  "velocity": "Áramlási sebesség (v)",
  "velocityDesc": "Drasztikusan befolyásolja a nyomásveszteséget és a szivattyú energiafogyasztását (B).",
  "fluidTemp": "Folyadék hőmérséklete",
  "ambientTemp": "Környezeti hőmérséklet",
  "insulation": "Szigetelés",
  "insulationNone": "Nincs",
  "insulationBasic": "Alap",
  "insulationStandard": "Standard EnEV",
  "insulationPremium": "Prémium",
  "installMethod": "Fektetési mód (A5)",
  "installBuilding": "Épületgépészet",
  "installTrench": "Földbe fektetett (Kotró)",
  "installTrenchless": "Árok nélküli (HDD)",
  "installDesc": "A földmunkák hatalmas CO₂-kibocsátást okoznak a gépek (dízel) miatt.",
  "lifespan": "Élettartam (Év)",
  "lifespanDesc": "A rövid élettartamú csöveket (pl. szénacél) akár többször is cserélni kell.",
  "energyMixLabel": "Energiamix (Üzemeltetés és Termelés)",
  "transportKm": "Szállítási távolság (km)",
  "co2Savings": "LCA CO₂-Megtakarítás",
  "co2SavingsDesc": "A legkevésbé hatékony rendszerhez képest (beleértve a szivattyú áramát). Körülbelül {n} fának felel meg.",
  "costSavings": "TCO Megtakarítás (NPV)",
  "costSavingsDesc": "Megtakarítás {n} év alatt (beleértve a karbantartást és az üzemeltetési költségek jelenértékét).",
  "lcaPhases": "LCA Fázisok (EN 15804)",
  "phaseA13": "A1-A3 (Anyag)",
  "phaseA45": "A4-A5 (Telepítés/Szállítás)",
  "phaseB": "B (Üzemeltetés/Energia)",
  "phaseC": "C (EoL - Életciklus vége)",
  "moduleD": "D Modul:",
  "costAnalysis": "Teljes Birtoklási Költség (NPV, {n} Év)",
  "costMaterial": "Anyag",
  "costInstall": "Telepítés",
  "costOperation": "Energia (NPV)",
  "costMaintenance": "Karbantartás",
  "costTotal": "Összesen",
  "certTitle": "Minősített LCA és TCO Jelentés.",
  "certDesc": "Tartalmazza az áramlási ellenállást a Darcy-Weisbach egyenlet szerint és az EPD-nek megfelelő életciklus-fázisokat.",
  "certBtn": "PDF Jelentés Generálása",
  "generating": "Generálás...",
  "energyGreen": "Zöld Energia",
  "energyDe": "DE-Mix",
  "energyEu": "EU-Mix",
  "energyGlobal": "Globális-Mix",
  "materials": {
    "kaqua": "K-Aqua PPRCT",
    "pvc": "PVC-U",
    "copper": "Réz",
    "steel": "Rozsdamentes acél / Szénacél",
    "pex": "Többrétegű cső (PEX)",
    "pehd": "PE 100 (HDPE)",
    "castiron": "Öntöttvas"
  },
  "project": "Az Ön projektje",
  "advanced": "Fejlett LCA Paraméterek",
  "tempMode": "Üzemi hőmérséklet",
  "tempCold": "Hidegvíz (10°C)",
  "tempHot": "Melegvíz (60°C)",
  "recycle": "Életciklus végi újrahasznosítási jóváírás engedélyezése",
  "disclaimer": "A számítások validált, III. típusú EPD-ken (EN 15804) és az ecoinvent adatbázison alapulnak (A1-A3, A4, B, C1-C4).",
  "savedLabel": "CO₂e Megtakarítás a legjobb alternatívához képest",
  "savedBody1": "Egyenértékű a következők CO₂ elnyelésével:",
  "trees": "{n} fa",
  "or": "vagy",
  "carKm": "{n} autókilométer",
  "compareTitle": "Életciklus-értékelés (LCA)",
  "phases": {
    "a13": "Termelés (A1-A3)",
    "a4": "Szállítás (A4)",
    "b": "Üzemeltetés/Termikus (B)",
    "c": "Életciklus vége (C)"
  },
  "auditor": "Auditor pilótafülke:",
  "auditorBody": "EPD bizonyítékok, ISO tanúsítványok és GAEB szövegek egy csomagban, itt:",
  "trustLink": "Trust Center",
  "downloadPdf": "PDF Jelentés Letöltése",
  "lcaLogistics": "LCA és Logisztikai Paraméterek",
  "energyMix": "Termelési Energiamix",
  "transportMode": "Szállítási Mód",
  "transportTruck": "Teherautó",
  "transportShip": "Hajó",
  "transportAir": "Légi Teherszállítás",
  "phaseProduction": "Termelés (A1-A3)",
  "phaseTransport": "Szállítás (A4)",
  "phaseOperation": "Üzemeltetés (B)",
  "phaseEol": "Életciklus vége (C1-C4)"
}`;

const replacement = '  "co2": ' + JSON.stringify(JSON.parse(repl), null, 2).split('\n').join('\n  ') + ',';

const req = {
  TargetFile: '/Users/umurey/Downloads/K-Aqua-V1-main/messages/hu.json',
  StartLine: 3181,
  EndLine: 3265,
  Instruction: 'Replace co2',
  Description: 'Update co2 object',
  AllowMultiple: false,
  TargetContent: target,
  ReplacementContent: replacement,
  toolSummary: 'Replace co2',
  toolAction: 'Replace co2'
};

fs.writeFileSync('mcp_co2.json', JSON.stringify(req, null, 2));
