const fs = require('fs');

const transitionFittings = {
  seoTitle: 'Átmeneti Idomok Sárgarézből és PP-R-ből',
  seoText: 'Az átmeneti idomok döntő hídként szolgálnak a K-Aqua fejlett PP-R/PPRCT csövei és a meglévő acél-, réz- vagy sárgaréz-alkatrészek között. Ezek a szerelvények rendkívüli mérnöki precizitást igényelnek.',
  advTitle: 'Biztonságos és homogén kötések',
  advList: [
    'A DZR sárgaréz betétek kiváló ellenállást nyújtanak a cinkkiválással szemben.',
    'A csavarodásgátló kialakítás ellenáll a magas nyomatéknak.',
    'A műanyag és a fém közötti elválaszthatatlan kapcsolat szivárgásmentes teljesítményt garantál.'
  ],
  guideText: '\n    <h2>A rés áthidalása</h2>\n    <p>Amikor a modern polimer rendszereket a hagyományos fémes infrastruktúrával kell összekapcsolni, a biztonságos és homogén kötések abszolút fontosságúak. Az átmeneti idomok döntő hídként szolgálnak a K-Aqua fejlett PP-R/PPRCT csövei és a meglévő acél-, réz- vagy sárgaréz-alkatrészek, például kazánok, hűtők és szaniter szerelvények között. Ezek a szerelvények rendkívüli mérnöki precizitást igényelnek annak érdekében, hogy a fém és a műanyag közötti kapcsolat extrém termikus ciklusok és mechanikai igénybevétel mellett is abszolút tömített maradjon.</p>\n    <p>A K-Aqua átmeneti idomok mélyen beágyazott, csavarodásbiztos DZR (Dezincification Resistant - cinkkiválással szemben ellenálló) sárgaréz betétekkel rendelkeznek. A fröccsöntési folyamat során a forró PP-R-t közvetlenül a sárgaréz betét összetett geometriai profiljára formálják. Amikor a műanyag lehűl és zsugorodik, hatalmas erővel tapad a sárgarézre, így oldhatatlan mechanikai kapcsolatot hozva létre. Ez a kialakítás megakadályozza, hogy a sárgaréz betét elforduljon vagy kihúzódjon, még akkor is, ha telepítéskor egy csőkulcs magas nyomatékának van kitéve.</p>\n    <p>Ezenkívül a kiváló minőségű DZR sárgaréz biztosítja, hogy az idom fémes része rendkívül ellenálló legyen az agresszív vízviszonyokkal szemben, megakadályozva az idő előtti korróziót, ami gyakran sújtja a szabványos sárgaréz idomokat. Ez különösen a melegvíz-rendszerekben kritikus, ahol a reakciósebesség jelentősen felgyorsul.</p>\n    <ul>\n      <li>A DZR sárgaréz betétek kiváló ellenállást nyújtanak a cinkkiválással és a korrózióval szemben.</li>\n      <li>A csavarodásgátló kialakítás könnyedén ellenáll a magas nyomatéknak a menetes szereléseknél.</li>\n      <li>A műanyag és a fém közötti elválaszthatatlan kapcsolat élethosszig tartó, szivárgásmentes teljesítményt garantál.</li>\n      <li>Széles választékban kapható külső és belső menetes konfigurációkkal.</li>\n      <li>Tökéletes a PP-R hálózatok fémes szivattyúkhoz, szelepekhez és kazánokhoz történő csatlakoztatására.</li>\n    </ul>\n    <p>Függetlenül attól, hogy egy masszív 125 mm-es ipari hűtővezetéket kell acélkarimához illesztenie, vagy egyszerűen egy 20 mm-es lakossági vízvezetéket egy króm sarokszelephez, a K-Aqua pontosan a szükséges átmeneti darabot kínálja.</p>\n  '
};

const valves = {
  seoTitle: 'Kiváló minőségű Szelepek PP-R rendszerekhez',
  seoText: 'A pontos szabályozás és a tartós működés elengedhetetlen. A K-Aqua nagy teljesítményű elzáró szelepeket és golyóscsapokat kínál PP-R csőrendszerekhez.',
  advTitle: 'Maximális biztonság és tartósság',
  advList: [
    'A teljes áteresztésű (Full Port) kialakítás megakadályozza az áramlás korlátozását.',
    'A korrózióálló műanyag házak védik a belső fém alkatrészeket.',
    'A közvetlen polifúzió kiküszöböli a menetes csatlakozások szükségességét.'
  ],
  guideText: '\n    <h2>Abszolút Áramlásszabályozás</h2>\n    <p>A pontos szabályozás és a hosszú élettartamú működés elengedhetetlen a modern szaniterhálózatok menedzseléséhez. A hatékony folyadékkezeléshez robusztus, megbízható ellenőrzési pontokra van szükség, amelyek zökkenőmentesen integrálhatók a fő elosztóhálózatba. A K-Aqua a nagy teljesítményű elzáró szerelvények átfogó választékát kínálja, beleértve a teljes áteresztésű golyóscsapokat, a falsík alatti szelepeket és a precíziós szelepeket, melyeket mind kifejezetten a PP-R csőrendszerekkel történő közvetlen polifúzióhoz fejlesztettek ki.</p>\n    <p>Azáltal, hogy a szeleptestet pontosan ugyanabból a PP-R polimerből gyártjuk, mint a környező csöveket, feleslegessé tesszük a menetes átmeneti idomokat az elzárópontok telepítésekor. Ez drasztikusan felgyorsítja a telepítési időt, csökkenti az anyagköltségeket, és megszünteti a rendszer potenciális gyenge pontjait. A belső mechanikus alkatrészek, mint a precíziós megmunkálású sárgaréz golyók, rozsdamentes acél orsók és kiváló minőségű teflon (PTFE) tömítőgyűrűk, úgy lettek kialakítva, hogy évtizedeken át hihetetlenül sima, karbantartásmentes működést biztosítsanak.</p>\n    <p>Szemben a hagyományos fémes tolózárakkal, amelyek gyakran megszorulnak vagy a tömszelencénél szivárognak az évekig tartó inaktivitás után, a K-Aqua műanyag tokozású szelepei immunisak a külső korrózióra. Ezáltal tökéletesek a nedves géptermekben, föld alatti telepítéseknél vagy párás ipari környezetben történő alkalmazásra.</p>\n    <ul>\n      <li>A teljes áteresztésű (Full Port) kialakítás megakadályozza a folyadékáramlás korlátozását.</li>\n      <li>A korrózióálló műanyag házak védik a belső fém alkatrészeket.</li>\n      <li>A közvetlen polifúzió feleslegessé teszi a sérülékeny csavarkötéseket.</li>\n      <li>Az ergonómikus fogantyúk és a finommechanika zökkenőmentes működést biztosít.</li>\n      <li>Széles méretválasztékban kaphatók, hogy mind a lakossági, mind az ipari igényeket kielégítsék.</li>\n    </ul>\n    <p>A teljes áteresztésű kialakításunk biztosítja, hogy nyitott szelep esetén a hidraulikus áramlás nem korlátozódik, ezáltal fenntartva az optimális rendszernyomást és maximalizálva a keringető szivattyúk hatékonyságát. Függetlenül attól, hogy egyetlen szaniter szerelvényt kell elszigetelnie, vagy egy kereskedelmi épület fő tápvezetékét kell szabályoznia, a K-Aqua szelepek garantálják a szükséges megbízhatóságot és teljesítményt.</p>\n    <p>Minden szelepet csomagolás előtt szigorú nyomáspróbáknak vetünk alá annak érdekében, hogy megfeleljenek kompromisszumot nem ismerő minőségi szabványainknak. Bízzon a K-Aquában, ha azokról az ellenőrző mechanizmusokról van szó, amelyekkel a folyadékhálózata nap mint nap és évről évre biztonságosan és hatékonyan működik.</p>\n  '
};

fs.writeFileSync('seo_insert.json', JSON.stringify({
  transitionFittings: transitionFittings,
  valves: valves
}, null, 2));
