const fs = require('fs');
const geo = JSON.parse(fs.readFileSync('id_geo.json'));
const keys = Object.keys(geo);
const half = Math.ceil(keys.length / 2);
const geo1 = {};
const geo2 = {};
keys.slice(0, half).forEach(k => geo1[k] = geo[k]);
keys.slice(half).forEach(k => geo2[k] = geo[k]);
fs.writeFileSync('geo1.json', JSON.stringify(geo1, null, 2));
fs.writeFileSync('geo2.json', JSON.stringify(geo2, null, 2));
