import json

with open('da_fixed.json', 'r', encoding='utf-8') as f:
    da = json.load(f)

# INDEX
index = da['solutions']['index']
index['sticky']['header']['title'] = "Fysisk Overlegenhed."
index['sticky']['header']['desc'] = "De tekniske principper, der giver K-AQUA systemer deres overlegne levetid og driftssikkerhed."
index['sticky']['items'][0]['title'] = "Molekylær Homogenitet"
index['sticky']['items'][0]['p1'] = "K-AQUA PPR-systemet er baseret på avanceret polyfusionsteknologi. Gennem præcist kalibreret opvarmning smelter rør og fitting sammen på molekylært niveau til en uadskillelig, sammenhængende enhed."
index['sticky']['items'][0]['p2'] = "Denne sømløse syntese eliminerer enhver svaghed, der uundgåeligt opstår med mekaniske forbindelser eller klæbeprocesser. Resultatet er en infrastruktur med absolut integritet, der ubesværet modstår hydrauliske stød og ekstreme trykspidser."
index['sticky']['items'][1]['title'] = "Termisk Udholdenhed"
index['sticky']['items'][1]['p1'] = "Termiske svingninger er konventionelle rørsystemers største fjende. K-AQUA polymerer er struktureret med et højdensitets krystalgitter, der forhindrer strukturelle deformationer selv ved permanente driftstemperaturer på op til 95°C."
index['sticky']['items'][1]['p2'] = "Materialets specifikke varmekapacitet reducerer desuden behovet for ekstrem isolering, hvilket øger hele systemets energieffektivitet markant."
index['sticky']['items'][2]['title'] = "Hydraulisk Perfektion"
index['sticky']['items'][2]['p1'] = "En absolut ruhedsværdi på blot 0,007 mm definerer den indvendige overflade af K-AQUA rør. Denne mikroskopisk glatte topografi forhindrer enhver inkrustation, mineralaflejringer eller biofilmdannelse."
index['sticky']['items'][2]['p2'] = "Strømningstab reduceres til et fysisk minimum, hvilket drastisk sænker pumpesystemers energibehov over årtier. Den konstante indvendige diameter garanterer en uophørlig, uformindsket gennemstrømningshastighed."
index['sticky']['items'][3]['title'] = "Kemisk Immunitet"
index['sticky']['items'][3]['p1'] = "I modsætning til metalliske systemer er K-AQUA PPR-netværket fuldstændig immunt over for oxidation, grubetæring og galvanisk korrosion. Copolymérens inerte egenskaber modstår et ekstremt bredt spektrum af meget aggressive kemikalier og varierende pH-værdier."
index['sticky']['items'][3]['p2'] = "Selv i stærkt korrosive industrielle miljøer eller ved transport af aggressive væsker forbliver rørets molekylære integritet intakt."
index['timeline']['items'][0]['title'] = "Strukturel Analyse"
index['timeline']['items'][0]['text'] = "Evaluering af termodynamiske og fluiddynamiske krav. Præcis beregning af trykklasser, termisk længdeudvidelse og hydraulisk modstand."
index['timeline']['items'][1]['title'] = "Materialesyntese"
index['timeline']['items'][1]['text'] = "Fremstilling af vores specifikke PP-R/PP-RCT granulat. Tilførsel af specielle antioxidanter og UV-stabilisatorer for maksimal levetid."
index['timeline']['items'][2]['title'] = "Molekylær Fusion"
index['timeline']['items'][2]['text'] = "Installationsfasen. Samling af komponenterne via termisk polyfusion ved 260°C. Skabelsen af et fuldstændig homogent, lækagefrit netværk."
index['timeline']['items'][3]['title'] = "Systemverifikation"
index['timeline']['items'][3]['text'] = "Omfattende hydrauliske trykprøver, ofte ved et testtryk, der ligger langt over det nominelle driftstryk, for at bekræfte den absolutte strukturelle integritet."
for i in range(4):
    index['timeline']['items'][i]['year'] = f"Fase 0{i+1}"
index['timeline']['title'] = "Realisering"
index['timeline']['desc'] = "Fra teknisk kravspecifikation til den ibrugtagne infrastruktur."
index['intro']['eyebrow'] = "Ingeniørkunst"
index['intro']['title'] = "Bygget til at overgå."
index['intro']['lead'] = "De teknologiske fordele ved K-Aqua PP-R går langt ud over traditionelle rørsystemer. Det er en holistisk løsning til den moderne civilisations kritiske kredsløb."
index['bento']['items'][0]['title'] = "100% Korrosionsfri"
index['bento']['items'][0]['desc'] = "Polypropylen reagerer ikke med vand eller ilt. Rust og grubetæring er fysisk umulige. Det sikrer absolut renhed og forhindrer rørskader."
index['bento']['items'][1]['title'] = "Sømløs Forbindelse"
index['bento']['items'][1]['desc'] = "Gennem polyfusionssvejsning smelter rør og fitting sammen på molekylært niveau. Ingen o-ringe, ingen utætheder, ingen svage punkter i netværket."
index['bento']['items'][2]['title'] = "Termisk & Akustisk Isolering"
index['bento']['items'][2]['desc'] = "Den lave varmeledningsevne minimerer energitab og kondens. Desuden dæmper materialet flowstøj betydeligt for en rolig bygningsakustik."
index['bento']['items'][3]['title'] = "Fremragende Levetid"
index['bento']['items'][3]['desc'] = "Designet til at holde hele bygningens levetid. K-Aqua systemer tilbyder en garanteret vedligeholdelsesfri levetid på over 50 år ved standardbetingelser."
index['cta']['title'] = "Klar til næste generations infrastruktur?"
index['cta']['desc'] = "Vores ingeniører står klar til at hjælpe dig med at dimensionere og specificere dit K-Aqua PP-R system."
index['cta']['button'] = "Kontakt Vores Ingeniører"
index['stats']['0']['label'] = "Års Garanteret Levetid"
index['stats']['0']['desc'] = "Under standard driftsforhold leverer K-Aqua systemer årtiers pålidelig drift uden mekanisk eller kemisk nedbrydning."
index['stats']['1']['label'] = "W/mK Varmeledningsevne"
index['stats']['1']['desc'] = "Ekstremt lav varmeledningsevne resulterer i overlegen isoleringsevne og minimerer utilsigtet varmetab."
index['stats']['2']['label'] = "mm Absolut Ruhed"
index['stats']['2']['desc'] = "Ultra-glatte indvendige overflader eliminerer friktion og inkrustation, hvilket sikrer optimal hydraulisk ydeevne."
index['stats']['title'] = "Kvantificerbar Ydeevne."

# KRANKENHAUS
k = da['solutions']['krankenhaus']
k['hero']['eyebrow'] = "Hygiejne Infrastruktur"
k['hero']['title1'] = "Nul."
k['hero']['title2'] = "Tolerance."
k['hero']['desc'] = "Når vandkvalitet beskytter menneskeliv. K Aqua leverer fuldstændig fri for døde rum, korrosions-immune PP-R rørsystemer til klinisk infrastruktur."
k['hero']['cta1'] = "Start klinikprojekt"
k['hero']['cta2'] = "Læs hygiejnerapport"
k['intro']['title'] = "Hvor én dråbe vand <br className=\"hidden md:block\"/> kan få systemet til at kollapse."
k['intro']['desc'] = "Totalentreprenører står over for et uløseligt paradoks i klinikprojekter: Enormt tidspres under byggeriet møder de strengeste hygiejnekrav. Et eneste dødt rum, en mikrorevne: og millioninvesteringer er i fare. Vi løser dette paradoks."
k['sticky']['items'][0]['title'] = "Legionella-forebyggelse på molekylært niveau"
k['sticky']['items'][0]['desc'] = "I kritisk hospitalsinfrastruktur er vandhygiejne et spørgsmål om overlevelse. Vores PP-R rørsystemer har porefrie overflader, der fysisk forhindrer biofilm."
k['sticky']['items'][1]['title'] = "Termisk desinfektion uden materialetræthed"
k['sticky']['items'][1]['desc'] = "Kliniske standarder kræver termisk desinfektion ved over 70°C. K Aqua PPR-systemet er designet til ekstreme termiske belastninger i årtier."
k['sticky']['items'][2]['title'] = "Absolut uigennemtrængelighed for lys"
k['sticky']['items'][2]['desc'] = "Vand i mørke er dødt vand for alger. Vores PP-R rør blokerer 100% lys, hvilket fratager mikroorganismer basis for liv."
k['sticky']['items'][3]['title'] = "Hurtig, vibrationsfri installation"
k['sticky']['items'][3]['desc'] = "Ved hospitalstilbygninger under drift er støj uacceptabelt. Vores polyfusionsteknologi skaber permanente samlinger på få sekunder – helt lydløst."
k['bento']['items'][0]['title'] = "Ingen korrosion"
k['bento']['items'][0]['desc'] = "Sygdomsfremkaldende stoffer kan ikke sætte sig i korrosionshuller, og tungmetaller frigives ikke."
k['bento']['items'][1]['title'] = "Homogen sammensmeltning"
k['bento']['items'][1]['desc'] = "Der er ingen o-ringe, der kan ældes eller koloniseres af bakterier."
k['bento']['items'][2]['title'] = "Toksikologisk harmløs"
k['bento']['items'][2]['desc'] = "Opfylder de højeste medicinske standarder. Vandets smag og lugt forbliver uberørt."
k['bento']['items'][3]['title'] = "Ingen døde rum"
k['bento']['items'][3]['desc'] = "Flowoptimerede fittings forhindrer stagnerende vand, hvor patogener kan formere sig."
k['cta']['title'] = "Sikre kliniske vandforsyninger."
k['cta']['desc'] = "Samarbejd med os for at designe et rørsystem, der overgår fremtidens hospitalsstandarder."
k['cta']['button'] = "Kontakt hygiejneeksperter"

with open('da_fixed.json', 'w', encoding='utf-8') as f:
    json.dump(da, f, ensure_ascii=False, indent=2)

