const fs = require('fs');
let text = fs.readFileSync('solutions_merged.json', 'utf8');

const replacements = {
  "Ahol a fém csőrendszerek kapitulálnak a korrózió, a lerakódások és a termikus anyagkifáradás miatt, ott kezdődik a K-AQUA működési tartománya. A Polypropylene Random Kopolimer (PP-R) infrastruktúráink újraírják a folyadékszállítás fizikai határait.": "Ahol a fém csőrendszerek kapitulálnak a korrózió, a lerakódások és a termikus anyagkifáradás miatt, ott kezdődik a K-AQUA működési tartománya. A Polypropylene Random Kopolimer (PP-R) infrastruktúráink újraírják a folyadékszállítás fizikai határait.",
  "Rendszerünk minden millimétere évtizedes anyagtudományi kutatás eredménye. Mi nem egyszerű csöveket szállítunk; hibátlan, monolitikus érhálózatokat építünk ki azokhoz a létesítményekhez, amelyek nem engedhetik meg maguknak a leállást. A sarkvidéki hidegtől a forrásban lévő ipari folyamatokig a K-AQUA a tökéletes architekturális válasz az extrém mérnöki kihívásokra.": "Rendszerünk minden millimétere évtizedes anyagtudományi kutatás eredménye. Mi nem egyszerű csöveket szállítunk; hibátlan, monolitikus érhálózatokat építünk ki azokhoz a létesítményekhez, amelyek nem engedhetik meg maguknak a leállást. A sarkvidéki hidegtől a forrásban lévő ipari folyamatokig a K-AQUA a tökéletes architekturális válasz az extrém mérnöki kihívásokra.",
  "Skalierbare Systemlösungen für spezialisierte Industrie- und TGA-Sektoren.": "Skálázható rendszermegoldások speciális ipari és épületgépészeti szektorokhoz.",
  "Leckagefreie Übertragung bei extremen Betriebsdrücken. Keine Kontamination der Druckluft durch Rost oder abplatzende Partikel.": "Szivárgásmentes átvitel extrém üzemi nyomásokon. Nincs a sűrített levegő szennyeződése rozsda vagy leváló részecskék miatt.",
  "Widersteht salzhaltiger Umgebung und massiven Vibrationen. Signifikante Gewichtsreduktion im Vergleich zu Stahl-Installationen.": "Ellenáll a sós környezetnek és a masszív rezgéseknek. Jelentős súlycsökkentés az acél telepítésekhez képest.",
  "Kompromisslose Performance beim Transport von aggressiven Chemikalien, abrasiven Slurries oder hochreinen Prozessfluiden. Das K AQUA System garantiert ungestörte, sichere Produktion.": "Kompromisszumok nélküli teljesítmény agresszív vegyszerek, abrazív iszapok vagy nagy tisztaságú folyamatfolyadékok szállítása során. A K-AQUA rendszer garantálja a zavartalan, biztonságos termelést.",
  "Unter normalen Betriebsbedingungen (20°C / 10 Bar) überschreiten K AQUA PP-R Systeme mühelos ein halbes Jahrhundert Lebensdauer ohne signifikante Materialermüdung.": "Normál üzemi feltételek mellett (20°C / 10 bar) a K-AQUA PP-R rendszerek tartóssága könnyedén meghaladja a fél évszázadot, bármilyen jelentős anyagromlás nélkül.",
  "Im Vergleich zu Kupfer (380 W/mK) oder Stahl (50 W/mK) isoliert K AQUA von Natur aus, was zu massiven Einsparungen bei externer Dämmung und thermischen Verlusten führt.": "A rézhez (380 W/mK) vagy az acélhoz (50 W/mK) képest a K-AQUA természetéből fakadóan szigetel, ami jelentős megtakarítást eredményez a külső szigetelésben és a hőveszteségekben.",
  "Homogene Verbindungen": "Homogén kötések",
  "Durch die molekulare Verschweißung entsteht ein komplett fugenloses System. Rohr und Fitting verschmelzen zu einem einzigen, untrennbaren Bauteil.": "A molekuláris hegesztés révén egy teljesen hézagmentes rendszer jön létre. A cső és az idom egyetlen, elválaszthatatlan alkatrésszé olvad össze.",
  "Engineering in Zahlen.": "Mérnöki Munka Számokban.",
  "IN DIE NÄCHSTE DIMENSION.": "KÖVETKEZŐ DIMENZIÓRA.",
  "Kontaktieren Sie unsere Ingenieure für ein tiefgreifendes technisches Assessment Ihrer Spezifikationen und Herausforderungen.": "Lépjen kapcsolatba mérnökeinkkel az Ön specifikációinak és kihívásainak részletes műszaki értékeléséhez.",
  "Engineering Team kontaktieren": "Mérnöki csapat kapcsolatfelvétele",
  "Rechenzentrums Infrastruktur | K-Aqua": "Adatközponti Infrastruktúra | K-Aqua",
  "K-Aqua Rechenzentren: Kompromisslose Sicherheit durch German Engineering für globale Megaprojekte. Entdecken Sie unsere Kühllösungen für Data Center.": "K-Aqua Adatközpontok: Kompromisszumok nélküli biztonság a német mérnöki munkának köszönhetően globális megaprojektek számára. Fedezze fel adatközpontokhoz kínált hűtési megoldásainkat.",
  "Moderne High-Performance Computing (HPC) und Artificial Intelligence (AI) Racks erzeugen immense Abwärme. Luftkühlung allein gerät an physikalische Grenzen. Die Zukunft ist Liquid Cooling – und Wasser als entscheidendes Transportmedium rückt direkt an die Chips heran.": "A modern High-Performance Computing (HPC) és a Mesterséges Intelligencia (AI) rack-ek hatalmas mennyiségű hulladékhőt termelnek. A légkondicionálás önmagában fizikai határaihoz ér. A jövő a folyadékhűtésé (Liquid Cooling), ahol a víz kulcsfontosságú hőátadó közegként jelenik meg, közvetlenül a chipek mellett.",
  "Metallische Rohrnetze unterliegen im Dauerbetrieb Lochfraß, Rost und chemischer Zersetzung. Ein einziger mikroskopischer Haarriss im Rechenzentrum führt durch Server-Ausfall zu Millionenschäden. K Aqua eliminiert dieses Risiko durch 100% korrosionsresistente Polypropylen Random Copolymer (PP-R) Technologie.": "A fém csőhálózatok folyamatos működés során lyukkorróziónak, rozsdásodásnak és kémiai bomlásnak vannak kitéve. Egyetlen mikroszkopikus repedés az adatközpontban milliós károkat okozhat a szerverek leállása miatt. A K-Aqua kiküszöböli ezt a kockázatot a 100%-ban korrózióálló Polypropylene Random Kopolimer (PP-R) technológiával.",
  "Wo traditionelle Leitungen auf fehleranfällige Dichtungen oder Schraubgewinde vertrauen, verschmelzen K Aqua Systeme auf molekularer Ebene. Das Ergebnis: Ein absolut fugenloses, hermetisch dichtes Rohrnetz. Null Toleranz für Leckagen.": "Ahol a hagyományos csövek hibára hajlamos tömítésekre vagy csavarkötésekre támaszkodnak, ott a K-Aqua rendszerek molekuláris szinten olvadnak össze. Az eredmény: egy teljesen homogén, abszolút szivárgásmentes csőhálózat. Nulla tolerancia a szivárgásokkal szemben.",
  "Ein niedriger PUE-Wert (Power Usage Effectiveness) ist der heilige Gral der Data Center Betreiber. K Aqua Rohre besitzen überragende thermodynamische Eigenschaften. Geringere Reibungsverluste und optimale thermische Isolation minimieren den Energieverlust beim Transport des Kühlwassers massiv.": "Az alacsony PUE (Power Usage Effectiveness) érték az adatközpont-üzemeltetők Szent Grálja. A K-Aqua csövek kiváló termodinamikai tulajdonságokkal rendelkeznek. A kisebb súrlódási veszteségek és az optimális hőszigetelés nagymértékben minimalizálják az energiaveszteséget a hűtővíz-keringtetés során.",
  "Unsere Ingenieure analysieren die Kühlungsanforderungen des Rechenzentrums. Wir berechnen Volumenströme, eliminieren Flaschenhälse und dimensionieren das Rohrnetz für maximale hydrodynamische Effizienz.": "Mérnökeink elemzik az adatközpont hűtési követelményeit. Kiszámítjuk a térfogatáramokat, kiküszöböljük a szűk keresztmetszeteket, és úgy méretezzük a csőhálózatot, hogy az maximális hidrodinamikai hatékonyságot nyújtson.",
  "In unserem Stammwerk in Deutschland werden komplexe Verteilnetze (Spools) auf Maß vorgefertigt. Zentimetergenau, hochautomatisiert und qualitätsgeprüft unter Laborbedingungen.": "Németországi anyavállalatunknál az összetett elosztó rendszereket (Spools) méretre gyártjuk. Centiméteres pontossággal, teljesen automatizáltan és laboratóriumi körülmények között minőségbiztosítva.",
  "Megaprojekte dulden keinen Lieferverzug. Wir orchestrieren die globale Logistik direkt an die Baustelle, synchronisiert mit den strikten Zeitplänen der Generalunternehmer.": "A megaprojektek nem tűrik a szállítási késedelmeket. A globális logisztikát közvetlenül az építkezéshez koordináljuk, szinkronizálva a fővállalkozók szigorú ütemtervével.",
  "Lokale Installationsteams werden durch K Aqua Master Welder zertifiziert. Die molekulare Verschweißung vor Ort garantiert ein 100% leckagefreies, homogenes Leitungsnetz ohne Schwachstellen.": "A helyi telepítőcsapatokat K-Aqua Mesterhegesztők vizsgáztatják. A helyszíni molekuláris hegesztés 100%-ban szivárgásmentes, homogén, gyenge pontok nélküli vezetékrendszert garantál.",
  "Vor der Übergabe erfolgt ein gnadenloser hydraulischer Druck- und Stresstest. Nur bei absolutem Bestehen erteilen wir die Freigabe und übernehmen die volle Systemgarantie.": "Átadás előtt könyörtelen hidraulikus nyomás- és terheléspróbát hajtunk végre. Csak a tesztek sikeres teljesítése után adjuk meg a hozzájárulást és vállaljuk a teljes rendszergaranciát.",
  "Der Engineering Prozess": "A Mérnöki Folyamat",
  "Vom hydrodynamischen Entwurf bis zur finalen Abnahme: Wie wir globale Hyperscale Infrastrukturen ohne Kompromisse in Rekordzeit realisieren.": "A hidrodinamikai vázlattól a végső átvételig: hogyan valósítjuk meg a globális Hyperscale infrastruktúrákat kompromisszumok nélkül, rekordidő alatt.",
  "Wenn Kühlsysteme das Herzblut globaler Rechenzentren sind, ist Materialversagen keine Option. Entdecken Sie das sicherste, effizienteste und skalierbarste PP-R Rohrnetz für geschäftskritische Kälte- und Klimatechnik.": "Amikor a hűtőrendszerek a globális adatközpontok szívét jelentik, az anyaghiba nem opció. Fedezze fel a legbiztonságosabb, leghatékonyabb és legjobban skálázható PP-R csőrendszert az üzletkritikus hűtési és klímatechnológiákhoz.",
  "Mission Critical Cooling": "Küldetéskritikus Hűtés",
  "Warum traditionelle Rohre scheitern.": "Miért buknak el a hagyományos csövek?",
  "Die Anforderungen moderner Hyperscaler und KI-Cluster übersteigen die physikalischen Grenzen konventioneller Metallsysteme.": "A modern Hyperscalerek és a mesterséges intelligencia klaszterek követelményei meghaladják a hagyományos fémrendszerek fizikai határait.",
  "Die PP-R Überlegenheit": "A PP-R Fölénye",
  "Jedes atomare Detail unseres Systems ist auf absolute Ausfallsicherheit und Langlebigkeit optimiert.": "Rendszerünk minden atomi részletét az abszolút megbízhatóságra és tartósságra optimalizáltuk.",
  "Geschlossene Kühlkreisläufe verlangen Konditionierungsmittel. K Aqua verhält sich völlig inert gegenüber aggressiven Additiven und verhindert Algen- und Biofilmbildung vollständig. Keine chemische Zersetzung, keine Partikel im Kühlwasser.": "A zárt hűtőkörök kondicionáló szereket igényelnek. A K-Aqua teljesen inert az agresszív adalékanyagokkal szemben, és teljes mértékben megakadályozza az algák és a biofilmek képződését. Nincs kémiai bomlás, nincsenek részecskék a hűtővízben.",
  "Druckresistenz im Hochhausbau": "Nyomásállóság a Magasépületekben",
  "Konzipiert für permanente Spitzenlasten bei extremen PN10 / PN20 Druckverhältnissen in vertikalen High-Rise Rechenzentren.": "Folyamatos csúcsterhelésekre tervezték extrém PN10 / PN20 nyomásviszonyok között a vertikális magasépület-adatközpontokban.",
  "Wir verschweißen komplexe Verteilerblöcke in unserem deutschen Stammwerk vor. Plug-and-Play Lieferung für drastisch verkürzte Bauzeiten.": "Bonyolult elosztóblokkokat hegesztünk előre a németországi anyavállalatunknál. Plug-and-Play szállítás a drasztikusan lerövidített építési idők érdekében.",
  "Erdbebensicherheit (Seismic Resistance)": "Földrengésállóság (Seismic Resistance)",
  "Im Gegensatz zu starren Metallsystemen besitzt unser PP-R System eine definierte Eigenelastizität. Schockwellen von Notstromaggregaten, massive Vibrationen und starke seismische Aktivitäten werden absorbiert, anstatt zerstörerische Risse zu verursachen.": "A merev fémrendszerekkel ellentétben a mi PP-R rendszerünk definiált belső rugalmassággal rendelkezik. A vészhelyzeti áramfejlesztőktől származó lökéshullámokat és a masszív vibrációkat, valamint az erős szeizmikus aktivitást elnyeli ahelyett, hogy pusztító töréseket okozna.",
  "Bereit für kompromisslose Sicherheit?": "Készen áll a kompromisszumok nélküli biztonságra?",
  "Sprechen Sie mit unserem Engineering-Team. Wir analysieren Ihr nächstes Data Center Megaprojekt und konstruieren die Infrastruktur der Zukunft.": "Lépjen kapcsolatba mérnöki csapatunkkal. Kielemezzük az Ön következő adatközpont-megaprojektjét, és megépítjük a jövő infrastruktúráját.",
  "Engineering-Call vereinbaren": "Mérnöki Megbeszélés Egyeztetése"
};

for (let key in replacements) {
  text = text.replace(key, replacements[key]);
}

fs.writeFileSync('solutions_hu_final.json', text);
