const fs = require('fs');

const translated = {
  "co2": {
    "guideText": "A K-Aqua CO2 Kalkulátor lehetővé teszi a PP-R és a réz csőrendszerek kibocsátásának pontos összehasonlítását. Az életciklus-elemzési (LCA) adatok alapján számítjuk ki a környezeti lábnyomot.",
    "eyebrow": "Kalkulátor",
    "title1": "CO₂ Lábnyom",
    "titleGrad": "Elemzés.",
    "lead": "Számítsa ki projektje ökológiai hatását. Hasonlítsa össze a K-Aqua PP-R csőrendszereket a hagyományos anyagokkal életciklusuk során.",
    "tabGeometry": "Geometria",
    "tabFlow": "Áramlás",
    "tabEnvironment": "Környezet",
    "tabLogistics": "Logisztika",
    "dia": "Külső átmérő (mm)",
    "length": "Teljes hossz (m)",
    "sdrClass": "SDR osztály",
    "velocity": "Áramlási sebesség (m/s)",
    "velocityDesc": "Hatással van a nyomásveszteségre és a szivattyúzási energiára",
    "fluidTemp": "Folyadék hőmérséklete (°C)",
    "ambientTemp": "Környezeti hőmérséklet (°C)",
    "insulation": "Szigetelés",
    "insulationNone": "Nincs",
    "insulationBasic": "Alap",
    "insulationStandard": "Standard",
    "insulationPremium": "Prémium",
    "installMethod": "Telepítési módszer",
    "installBuilding": "Épületen belül",
    "installTrench": "Földárokban",
    "installTrenchless": "Árok nélküli",
    "installDesc": "Befolyásolja a telepítési fázis CO₂ kibocsátását",
    "lifespan": "Tervezett élettartam (Év)",
    "lifespanDesc": "Hatással van a karbantartási és csereciklusokra",
    "energyMixLabel": "Energiamix (Gyártás)",
    "transportKm": "Szállítási távolság (km)",
    "co2Savings": "CO₂ Megtakarítás",
    "co2SavingsDesc": "Tonna CO₂ egyenérték",
    "costSavings": "Költségmegtakarítás",
    "costSavingsDesc": "A teljes élettartam alatt",
    "lcaPhases": "LCA Fázisok (EN 15804)",
    "phaseA13": "A1-A3: Gyártás",
    "phaseA45": "A4-A5: Szállítás és Telepítés",
    "phaseB": "B: Használati fázis",
    "phaseC": "C: Életciklus vége",
    "moduleD": "D: Újrahasznosítási potenciál",
    "costAnalysis": "Költségelemzés",
    "costMaterial": "Anyagköltség",
    "costInstall": "Telepítés",
    "costOperation": "Üzemeltetés (Szivattyúzás)",
    "costMaintenance": "Karbantartás",
    "costTotal": "Teljes élettartam költség (TCO)",
    "certTitle": "EPD Tanúsítvány",
    "certDesc": "Minden adatunk harmadik fél által hitelesített Környezetvédelmi Terméknyilatkozatokon (EPD) alapul.",
    "certBtn": "EPD Letöltése",
    "generating": "Számítás folyamatban...",
    "energyGreen": "100% Zöld",
    "energyDe": "Német Mix",
    "energyEu": "EU Mix",
    "energyGlobal": "Globális Mix",
    "materials": "Anyagok",
    "project": "Projekt",
    "advanced": "Haladó",
    "tempMode": "Hőmérséklet mód",
    "tempCold": "Hidegvíz",
    "tempHot": "Melegvíz",
    "recycle": "Újrahasznosítás",
    "disclaimer": "Ezek a számítások közelítő jellegűek és a jelenlegi iparági átlagokon alapulnak. A pontos projekt-specifikus értékek eltérhetnek.",
    "savedLabel": "Megtakarítva",
    "savedBody1": "Ez a CO₂ mennyiség egyenértékű:",
    "trees": "fával (10 év alatt megkötött)",
    "or": "vagy",
    "carKm": "km autóúttal",
    "compareTitle": "PP-R vs Réz",
    "phases": "Fázisok",
    "auditor": "Hitelesített adatok",
    "auditorBody": "A K-Aqua CO₂ számításait független szakértők ellenőrzik.",
    "trustLink": "Tovább a Bizalom Központhoz",
    "downloadPdf": "Eredmények letöltése (PDF)",
    "lcaLogistics": "Logisztikai LCA",
    "energyMix": "Energiamix",
    "transportMode": "Szállítási mód",
    "transportTruck": "Teherautó",
    "transportShip": "Hajó",
    "transportAir": "Légi",
    "phaseProduction": "Gyártás (A1-A3)",
    "phaseTransport": "Szállítás (A4)",
    "phaseOperation": "Működés (B1-B7)",
    "phaseEol": "Életciklus vége (C1-C4)"
  }
};

const lines = JSON.stringify(translated, null, 2).split('\n');
const inner = lines.slice(1, -1).map(l => '  ' + l).join('\n');
fs.writeFileSync('replace_co2.txt', inner);
