// ERZEUGT — nicht von Hand ändern.
// Quelle: public/kaqua-3d/lib/registry.mjs
// Neu erzeugen mit: node scripts/sync-3d-registry.mjs
//
// Redaktionelle Ausnahmen (Varianten, die sich ein Modell teilen) stehen in
// lib/3d/aliases.ts und werden dort gepflegt.

export const GENERATED_SLUG_MAP: Record<string, string> = {
  "adaptor-socket-female-thread": "transition-fittings/adaptor-socket-female-thread",
  "adaptor-socket-male-thread": "transition-fittings/adaptor-socket-male-thread",
  "adjustable-battery-female-thread": "valves/adjustable-battery-female-thread",
  "backing-flange": "accessories/backing-flange",
  "ball-valve-pp": "valves/pp-r-ball-valve-ball-in-pp",
  "battery-female-thread": "valves/battery-female-thread",
  "butt-welding-machine-90-250": "tools/butt-welding-machine-90-250",
  "cap": "fittings/cap",
  "concealed-valve-chrome-heavy-part": "valves/concealed-valve-chrome-heavy-part",
  "concealed-valve-chrome-light-part": "valves/concealed-valve-chrome-light-part",
  "cross": "fittings/cross",
  "cross-over": "fittings/cross-over",
  "cross-over-pipe": "fittings/cross-over-pipe",
  "drilling-tool-for-weld-in-saddle": "tools/drilling-tool-for-weld-in-saddle",
  "elbow-45": "fittings/elbow-45",
  "elbow-45-female-male": "fittings/elbow-45-female-male",
  "elbow-90": "fittings/elbow-90",
  "elbow-90-female-male": "fittings/elbow-90-female-male",
  "elbow-90-male-thread": "transition-fittings/elbow-90-male-thread",
  "elbow-bracket-90-female-thread": "transition-fittings/elbow-bracket-90-female-thread",
  "elbow-wall-bracket-90-female-thread": "transition-fittings/elbow-wall-bracket-90-female-thread",
  "electrofusion-machine": "tools/electrofusion-machine",
  "electrofusion-socket": "fittings/electrofusion-socket",
  "elongation-pieces": "valves/elongation-pieces",
  "flange-adaptor": "fittings/flange-adaptor",
  "flat-gasket": "accessories/flat-gasket",
  "flat-gasket-for-unions": "accessories/flat-gasket-for-unions",
  "hand-welding-machine-20-32": "tools/hand-welding-machine-20-32",
  "hand-welding-machine-20-63": "tools/hand-welding-machine-20-63",
  "hand-welding-machine-mirror-50-125": "tools/hand-welding-machine-mirror-50-125",
  "k-fiber-pipe-pp-r-sdr-11": "pipes/k-fiber-pipe-pp-r-sdr-11",
  "k-fiber-pipe-pp-r-sdr-17": "pipes/k-fiber-pipe-pp-r-sdr-17",
  "k-fiber-pipe-pp-r-sdr-6": "pipes/k-fiber-pipe-pp-r-sdr-6",
  "k-fiber-pipe-pp-r-sdr-74": "pipes/k-fiber-pipe-pp-r-sdr-7-4",
  "k-fiber-pipe-pp-r-sdr-9": "pipes/k-fiber-pipe-pp-r-sdr-9",
  "k-fiber-pipe-pp-rct-sdr-74": "pipes/k-fiber-pipe-pp-rct-sdr-7-4",
  "k-fiber-uv-pipe-pp-r-sdr-74": "pipes/k-fiber-uv-pipe-pp-r-sdr-7-4",
  "k-fiber-uv-pipe-pp-rct-sdr-74": "pipes/k-fiber-uv-pipe-pp-rct-sdr-7-4",
  "k-fiberclima-pipe-pp-rct-sdr-11": "pipes/k-fiberclima-pipe-pp-rct-sdr-11",
  "k-pipe-pp-r-sdr-11": "pipes/k-pipe-pp-r-sdr-11",
  "k-pipe-pp-r-sdr-6": "pipes/k-pipe-pp-r-sdr-6",
  "k-pipe-pp-rct-sdr-74": "pipes/k-pipe-pp-rct-sdr-7-4",
  "k-pipe-purple-pp-r-sdr-11": "pipes/k-pipe-purple-pp-r-sdr-11",
  "metal-union-female-thread": "transition-fittings/metal-union-female-thread",
  "metal-union-female-thread-brass": "transition-fittings/metal-union-female-thread-brass",
  "metal-union-male-thread": "transition-fittings/metal-union-male-thread",
  "metal-union-male-thread-brass": "transition-fittings/metal-union-male-thread-brass",
  "pipe-clamps": "accessories/pipe-clamps",
  "pipe-cutter-20-40": "tools/pipe-cutter-20-40",
  "pipe-cutter-50-125": "tools/pipe-cutter-50-125",
  "pipe-cutter-50-125-114": "tools/pipe-cutter-50-125-114",
  "plug": "accessories/plug",
  "pp-r-ball-valve-brass": "valves/pp-r-ball-valve-brass",
  "reducing-bush": "fittings/reducing-bush",
  "reducing-tee": "fittings/reducing-tee",
  "repairing-plug": "tools/repairing-plug",
  "socket": "fittings/socket",
  "straight-seat-valve-green-handle": "valves/straight-seat-valve-green-handle",
  "tee": "fittings/tee",
  "tee-90-female-thread": "transition-fittings/tee-90-female-thread",
  "tee-90-female-thread-internal-valve": "valves/tee-90-female-thread-internal-valve",
  "tee-90-male-thread": "transition-fittings/tee-90-male-thread",
  "union": "transition-fittings/union",
  "weld-in-saddle": "weld-in-saddles/weld-in-saddle",
  "weld-in-saddle-female-thread": "weld-in-saddles/weld-in-saddle-female-thread",
  "weld-in-saddle-male-thread": "weld-in-saddles/weld-in-saddle-male-thread",
  "welding-machine-50-125": "tools/welding-machine-50-125",
  "welding-tool": "tools/welding-tool",
  "welding-tool-for-repairing-plug": "tools/welding-tool-for-repairing-plug",
  "welding-tool-for-weld-in-saddles": "tools/welding-tool-for-weld-in-saddles",
};

export const GENERATED_COUNT = 70;

/** Produkte im Katalog insgesamt — Quelle: kaqua-3d/produkt-registry.json. */
export const CATALOG_TOTAL = 71;
