import json

with open("az.json", "r") as f:
    az = json.load(f)

az["seoArticle"]["transitionFittings"]["guideText"] = "\n    <h2>Boşluğu aradan qaldırmaq</h2>\n    <p>Müasir polimer sistemləri ənənəvi metal infrastrukturla birləşdirərkən, təhlükəsiz və homogen birləşmələr mütləq əhəmiyyət kəsb edir. Keçid fitinqləri (Transition Fittings) K Aqua-nın qabaqcıl PP-R/PPRCT boruları və mövcud polad, mis və ya pirinç komponentlər (qazanlar, soyuducular, santexnika armaturları) arasında mühüm bir körpü rolunu oynayır. Metal və plastik arasındakı bağlantının kəskin termal dövrlər və mexaniki gərginlik altında belə tamamilə sızdırmaz qalmasını təmin etmək üçün bu fitinqlər müstəsna səviyyədə mühəndislik tələb edir.</p>\n    <p>K Aqua keçid fitinqləri dərinə yerləşdirilmiş, dönməyə qarşı davamlı DZR (Sinkləşməyə Davamlı) mis taxmalara malikdir. İnyeksiya qəlibləmə prosesində isti PP-R mis taxmanın mürəkkəb həndəsi profilinin ətrafında birbaşa qəliblənir. Plastik soyuduqca və büzüldükcə, mis hissəni nəhəng bir güclə tutur və beləliklə qırılmaz bir mexaniki bağ əmələ gətirir. Bu dizayn, quraşdırma zamanı santexnik açarının yüksək fırlanma anı (tork) tətbiq edildikdə belə mis hissənin fırlanmasının və ya çıxmasının qarşısını alır.</p>\n    <p>Bundan əlavə, yüksək keyfiyyətli DZR misi fitinqin metal hissəsinin aqressiv su şərtlərinə qarşı son dərəcə davamlı olmasını təmin edərək, standart mis fitinqlərdə tez-tez rast gəlinən vaxtından əvvəl korroziyanın qarşısını alır. Reaksiya sürətinin əhəmiyyətli dərəcədə sürətləndiyi isti su sistemlərində bu, xüsusilə vacibdir.</p>\n    <ul>\n      <li>DZR mis taxmalar sinkləşməyə və korroziyaya qarşı üstün müqavimət göstərir.</li>\n      <li>Dönməyə davamlı dizayn yivli quraşdırmalarda yüksək fırlanma anına (tork) asanlıqla tab gətirir.</li>\n      <li>Plastik və metal arasındakı qırılmaz əlaqə ömürlük, sızdırmaz performansı təmin edir.</li>\n      <li>Daxili və xarici yiv konfiqurasiyalarının geniş çeşidi mövcuddur.</li>\n      <li>PP-R şəbəkələrini metal nasoslara, klapanlara və qazanlara bağlamaq üçün mükəmməldir.</li>\n    </ul>\n    <p>İstər kütləvi 125 mm-lik sənaye soyutma xəttini polad flanşa uyğunlaşdırmalı, istərsə də 20 mm-lik yaşayış suyu xəttini xromlanmış künc klapanına birləşdirməlisinizsə, K Aqua sizə tam tələb olunan keçid parçasını təklif edir.</p>\n  "

az["seoArticle"]["fittings"] = {
  "seoTitle": "PP-R Fitinqlər & Birləşmələr | K Aqua Boru Sistemi",
  "seoText": "Təhlükəsiz içməli su və isitmə quraşdırmaları üçün DVGW sertifikatlı K Aqua PP-R fitinqləri. Molekulyar səviyyədə sızdırmaz birləşmələr, maksimum uzunömürlülük.",
  "guideText": "\n    <h2>Polifüzyonun Gücü</h2>\n    <p>PP-R və PPRCT sistemlərinin uzunömürlülüyünün sirri birləşdirmə texnologiyasındadır: Polifüzyon qaynağı. Yapışqanlara, mexaniki sıxışdırmalara və ya rezin o-ringlərə əsaslanan ənənəvi sistemlərdən fərqli olaraq, K Aqua fitinqləri (Fittings) birbaşa borunun özü ilə qüsursuz, homogen şəkildə birləşir.</p>\n    <p>Boru və fitinq eyni vaxtda 260°C-yə qədər qızdırılır və sonra bir-birinə itələnir. Soyuduqda, onlar vahid, qırılmaz bir polimer zəncirinə çevrilirlər. O-ringlərin zamanla deqradasiyaya uğrama, yapışqanın zəifləmə və ya metal kəmərlərin korroziya riski yoxdur. Bir K Aqua qaynağı edildikdən sonra, birləşmə borunun özü qədər möhkəm olur.</p>\n    <p>Bizim mürəkkəb formalı fitinqlərimiz (Dirsəklər, Tee-lər, Reduksiyalar və s.) suyun turbulentliyini və təzyiq itkisini minimuma endirmək üçün hidro-dinamik cəhətdən optimallaşdırılmışdır. Geniş radiuslar və ultra-hamar daxili səthlər sayəsində mayelər minimum sürtünmə ilə axır və beləliklə enerji səmərəliliyini artırır.</p>\n    <ul>\n      <li>O-ring və ya mexaniki sızdırmazlıq olmadan 100% homogen qaynaq.</li>\n      <li>Aşağı təzyiq itkisi üçün hidro-dinamik optimallaşdırılmış dizayn.</li>\n      <li>Kimyəvi korroziyaya, ərpin və biofilmin əmələ gəlməsinə qarşı immunitet.</li>\n      <li>İsti və soyuq su paylanması üçün DVGW tərəfindən sertifikatlaşdırılmışdır.</li>\n      <li>Korroziyaya uğramaq riski olmadan nəsillər boyu etibarlı işləmə.</li>\n    </ul>\n    <p>K Aqua fitinqləri təkcə istiqaməti dəyişdirmir – onlar sisteminizin ümumi bütövlüyünü təmin edir və hər bir qovşağın onilliklər boyu təzyiq altında dayanmasına zəmanət verir.</p>\n  "
}

az["seoArticle"]["weldInSaddles"] = {
  "seoTitle": "PP-R Borular üçün Qaynaq Yəhərləri & Budaqlar",
  "seoText": "K Aqua qaynaq yəhərləri, xətti kəsmədən asan və təhlükəsiz şəkildə sonradan budaqlar çəkməyə imkan verir. Minimum quraşdırma vaxtı və maksimum sistem bütövlüyü.",
  "guideText": "\n    <h2>Asan Şaxələndirmə</h2>\n    <p>Mövcud bir boru kəmərinin genişləndirilməsi və ya dəyişdirilməsi məsələsində Weld-in Saddles (Qaynaq yəhərləri) maksimum elastiklik üçün misilsiz bir həll təqdim edir. K Aqua-nın qaynaq yəhərləri mövcud PP-R və PPRCT şəbəkələrində yeni budaqlar yaratmaq üçün innovativ və yüksək səmərəli bir üsuldur. Əsas borunun böyük bir hissəsini kəsmək və bahalı bir T-birləşmə quraşdırmaq əvəzinə, yəhər vasitəsilə sadəcə borunun yan tərəfində bir deşik aça və budağı birbaşa xarici divara qaynaq edə bilərsiniz.</p>\n    <p>Bu proses, xüsusilə böyük diametrli sənaye boruları ilə işləyərkən çoxlu vaxt, əmək və materiala qənaət edir. Yəhər əsas borunun əyriliyinə mükəmməl uyğunlaşdırılmış konkav bazaya malikdir və polifüzyon prosesi üçün geniş səth sahəsini təmin edir. Qaynaq edildikdən sonra yəhər əsas borunun daimi, ayrılmaz hissəsinə çevrilir və fabrikdə qəliblənmiş T-birləşmə ilə tam olaraq eyni möhkəmlik və təzyiq müqavimətinə malik olur.</p>\n    <p>Köhnə binaları yenidən quran və ya aktiv bir maşın otağına yeni avadanlıqlar əlavə edən podratçılar üçün qaynaq yəhərləri əsl xilaskardır. Onlar borunun ətrafında əhəmiyyətli dərəcədə az yer tələb edir və böyük bir kəsici aləti manevr etməyin mümkün olmadığı dar yerlərdə belə dəyişikliklərə imkan verir.</p>\n    <ul>\n      <li>Böyük diametrli T-birləşmələrlə müqayisədə material xərclərini kəskin şəkildə azaldır.</li>\n      <li>Yenidənqurma və sistemin genişləndirilməsi zamanı kəsilmə müddətini minimuma endirir.</li>\n      <li>Cihazla dolu olan maşın otaqlarında quraşdırma üçün daha az fiziki yer tələb edir.</li>\n      <li>Əsas xəttin struktur bütövlüyünü və təzyiq dərəcəsini qoruyur.</li>\n      <li>Sensorlara və ya klapanlara birbaşa qoşulmaq üçün mis yivli taxmalarla da mövcuddur.</li>\n    </ul>\n    <p>Biz yəhərlərimizlə xüsusi istifadə üçün nəzərdə tutulmuş xüsusi qazma alətləri və konturlu qızdırıcı matrislər təklif edirik. Bu, hər bir dəliyin mükəmməl dairəvi olmasını və hər bir qaynaq tikişinin bərabər şəkildə qızdırılmasını təmin edərək hər dəfə qüsursuz, sızdırmaz bir birləşməyə zəmanət verir. Bizim qaynaq yəhərlərimiz K Aqua-nın praktik, ağıllı mühəndislik öhdəliyini özündə təcəssüm etdirir.</p>\n    <p>İstər yeni bir sensor bağlantısı, istər drenaj xətti, istərsə də tamamilə yeni bir kollektor budağı əlavə etsəniz, K Aqua qaynaq yəhərləri işi ilk dəfədən düzgün etmək üçün tələb olunan struktur gücü və əməliyyat sadəliyini təmin edir.</p>\n  "
}


with open("az.json", "w") as f:
    json.dump(az, f, indent=2, ensure_ascii=False)
